### PR TITLE
german translation

### PR DESCRIPTION
**Pull request by uDEV2019**
But you have to change the character encoding of the application, because german umlauts are not display correctly

image

### CODE REVIEW

**Comment by r57zone** [comment]
Thank you very much! I will include it in the next release

**Comment by r57zone** [comment]
@uDEV2019 Hi, I added the translation to the latest version archive, but I don’t yet know how to implement it correctly. Maybe resaving UTF8 Ini in Ansi will be the right decision? Will the required characters be displayed in German?

Have you changed the encoding in the project properties? This path probably won’t work, since there are other languages.

**Comment by uDEV2019** [comment]
@r57zone When i pulled the request i already tested changing the encoding of the translation file only. Tested ANSI, UTF-8 (default of english.ini) and UTF-8 BOM. In the project itself i didn't change the properties.

**Comment by r57zone** [comment]
Could you then check the latest version to see if everything is fine with the German language? Thank you

**Comment by uDEV2019** [comment]
Ok, maybe i did something wrong when i tested this.
Saved the german.ini again with ansi encoding and now the umlauts are displayed right.

image

Did a new PR...

**Comment by r57zone** [comment]
I updated the file in the Portable archive, I hope everything is correct now, thank you.

**Pull request merged**
